services:
  db-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-workflow
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    # Quitamos el Healthcheck complejo que te está dando problemas

  api-workflow:
    build: .
    container_name: api-task-workflow
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - db-server # Solo esperamos a que el contenedor exista

volumes:
  mssql_data: